### ISSUE TITLE
Possible to add Python code

### ISSUE THREAD

**Issue by SaddamBInSyed** [Daniel595/Jetson_nano_face_recognition#1]
Hi. 

thanks for your work.

since I know the only python Is there any possibility to include python sample code to use this library?

Highly appreciated your help.

**Comment by Daniel595** [comment]
Hi.

I'm sorry that you can't use the C++ application. I probably won't find time to do this in python myself. It was content of a project which is finished now. 

When I started I actually wanted to use python too but I couldn't find a  python implementation of a face detector for jetson nano with satisfying performance. While implementing my app @jkjung-avt published a [TRT-implementation of MTCNN](https://github.com/jkjung-avt/tensorrt_demos#mtcnn). I would start with this one if I would implement it in Python. 

Jkjung posts interesting ML-projects frequently. Maybe he will do (or already did?) a face recognition in python.

**Comment by SaddamBInSyed** [comment]
Thanks @Daniel595 .
I found something.
